mode: ContinuousDeployment
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatch
increment: Patch

branches:
  main:
    regex: ^main$
    increment: Patch
    is-mainline: true
  develop:
    regex: ^dev(elop)?(/.+)?$
    tag: alpha
    increment: Minor
  feature:
    regex: ^features?[/-]
    tag: beta
    increment: Inherit
ignore:
  sha: []
