name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Answers.sln

    - name: Build
      run: dotnet build --no-restore Answers.sln

    - name: Run tests
      run: dotnet test --no-build --collect:"XPlat Code Coverage" --settings coverlet.runsettings

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: Answers.Tests/TestResults/**/*.xml

